#include "unity.h"

void test_accordion_item_reports_active_when_selected(void);
void test_avatar_ex_emits_draw_commands(void);
void test_button_ex_returns_zero_without_press(void);
void test_checkbox_does_not_toggle_without_press(void);
void test_checkbox_group_begin_end_restore_scope_and_indent(void);
void test_section_ex_unfolded_is_active(void);
void test_context_menu_begin_after_open_is_active(void);
void test_dialog_begin_respects_open_flag(void);
void test_fieldset_and_form_balance_scope(void);
void test_paragraph_and_label_emit_commands(void);
void test_panel_begin_end_balances_frame_stack(void);
void test_popover_begin_after_summon_is_active(void);
void test_popup_begin_after_summon_is_active(void);
void test_preview_card_begin_when_hovered_is_active(void);
void test_progress_and_meter_emit_commands(void);
void test_radio_does_not_change_selection_without_press(void);
void test_scroll_area_begin_end_balances_frame_stack(void);
void test_select_returns_zero_without_click(void);
void test_separator_emits_line_command(void);
void test_slider_clamps_value_to_range(void);
void test_switch_does_not_toggle_without_press(void);
void test_tabs_without_press_keep_selection(void);
void test_textfield_raw_appends_input_when_focused(void);
void test_theme_builder_applies_mutations(void);
void test_toggle_does_not_flip_without_press(void);
void test_toggle_group_without_press_keeps_selection(void);
void test_toolbar_begin_end_balances_grid_depth(void);
void test_tooltip_emits_overlay_when_anchor_is_hovered(void);
void test_window_begin_end_works_standalone(void);
void test_command_pipeline_walk_returns_draw_commands(void);
void test_textfield_enter_returns_commit_and_clears_focus(void);
void test_theme_change_affects_rendered_fill_color_next_frame(void);

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_accordion_item_reports_active_when_selected);
    RUN_TEST(test_avatar_ex_emits_draw_commands);
    RUN_TEST(test_button_ex_returns_zero_without_press);
    RUN_TEST(test_checkbox_does_not_toggle_without_press);
    RUN_TEST(test_checkbox_group_begin_end_restore_scope_and_indent);
    RUN_TEST(test_section_ex_unfolded_is_active);
    RUN_TEST(test_context_menu_begin_after_open_is_active);
    RUN_TEST(test_dialog_begin_respects_open_flag);
    RUN_TEST(test_fieldset_and_form_balance_scope);
    RUN_TEST(test_paragraph_and_label_emit_commands);
    RUN_TEST(test_panel_begin_end_balances_frame_stack);
    RUN_TEST(test_popover_begin_after_summon_is_active);
    RUN_TEST(test_popup_begin_after_summon_is_active);
    RUN_TEST(test_preview_card_begin_when_hovered_is_active);
    RUN_TEST(test_progress_and_meter_emit_commands);
    RUN_TEST(test_radio_does_not_change_selection_without_press);
    RUN_TEST(test_scroll_area_begin_end_balances_frame_stack);
    RUN_TEST(test_select_returns_zero_without_click);
    RUN_TEST(test_separator_emits_line_command);
    RUN_TEST(test_slider_clamps_value_to_range);
    RUN_TEST(test_switch_does_not_toggle_without_press);
    RUN_TEST(test_tabs_without_press_keep_selection);
    RUN_TEST(test_textfield_raw_appends_input_when_focused);
    RUN_TEST(test_theme_builder_applies_mutations);
    RUN_TEST(test_toggle_does_not_flip_without_press);
    RUN_TEST(test_toggle_group_without_press_keeps_selection);
    RUN_TEST(test_toolbar_begin_end_balances_grid_depth);
    RUN_TEST(test_tooltip_emits_overlay_when_anchor_is_hovered);
    RUN_TEST(test_window_begin_end_works_standalone);
    RUN_TEST(test_command_pipeline_walk_returns_draw_commands);
    RUN_TEST(test_textfield_enter_returns_commit_and_clears_focus);
    RUN_TEST(test_theme_change_affects_rendered_fill_color_next_frame);
    return UNITY_END();
}
